import type { AppProps } from "next/app";

import { withAuthenticator } from "@aws-amplify/ui-react";
import { Amplify } from "aws-amplify";
import config from "@/amplifyconfiguration.json";
import "@/styles/globals.css";

import {
  MyThemeProvider,
  ToastProvider,
  ConfettiProvider,
  ReactQueryProvider,
} from "@/providers";

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config, {
  ssr: true, // required when using Amplify with Next.js
});

import type { WithAuthenticatorProps } from "@aws-amplify/ui-react";

function App({
  Component,
  pageProps,
  user,
}: AppProps & WithAuthenticatorProps) {
  return (
    <MyThemeProvider>
      <ToastProvider />
      <ConfettiProvider />
      <ReactQueryProvider pageProps={pageProps}>
        <Component {...pageProps} user={user} />
      </ReactQueryProvider>
    </MyThemeProvider>
  );
}

export default withAuthenticator(App);
