import type { AppProps } from "next/app";

import { withAuthenticator } from "@aws-amplify/ui-react";
import { Amplify } from "aws-amplify";
import config from "@/amplifyconfiguration.json";
import { ToastProvider } from "@/providers/toaster-provider";
import "@/styles/globals.css";

import { MyThemeProvider } from "@/providers/my-theme-provider";

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config, {
  ssr: true, // required when using Amplify with Next.js
});

function App({ Component, pageProps }: AppProps) {
  return (
    <MyThemeProvider>
      <ToastProvider />
      <Component {...pageProps} />
    </MyThemeProvider>
  );
}

export default withAuthenticator(App);
